name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "eriksengrace" --password-stdin
          docker build -t cool_docker .
          docker tag cool_docker eriksengrace/nice_docker:latest
          docker push eriksengrace/nice_docker:latest

      - name: Create kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config

      - name: Check current context
        run: |
          kubectl config current-context
          kubectl config view --minify
          kubectl get nodes

      - name: Restart deployment
        run: |
          kubectl rollout restart deployment cst407-deployment